// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your api key',
    appId: 'your app id',
    messagingSenderId: 'your sender id',
    projectId: 'your firebase project id',
    authDomain: 'your-domain.firebaseapp.co',
    storageBucket: 'your-bucket.firebasestorage.app',
    measurementId: 'Measurement ıd',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your api key',
    appId: 'your app id',
    messagingSenderId: 'your sender id',
    projectId: 'Your Fireabse project id',
    storageBucket: 'your-bucket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your api key',
    appId: 'your app id',
    messagingSenderId: 'your sender id',
    projectId: 'Your Firebase Project id',
    storageBucket: 'your-bucket.firebasestorage.app',
    iosBundleId: 'com.circliks.blackflipper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your api key',
    appId: 'your app id',
    messagingSenderId: 'your sender id',
    projectId: 'Your Firebase Project id',
    storageBucket: 'your-bucket.firebasestorage.app',
    iosBundleId: 'com.circliks.blackflipper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your sender id',
    projectId: 'Your Firebase Project id',
    authDomain: 'your-domain.firebaseapp.com',
    storageBucket: 'your-bucket.firebasestorage.app',
    measurementId: 'Measurement id',
  );
}
