// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pcfeXc-JVV_y0LyY-iFG1IYaSK0CKH4',
    appId: '1:705573486453:web:bd0551209a1ac733ab9d3c',
    messagingSenderId: '705573486453',
    projectId: 'blackflipper-ecb71',
    authDomain: 'blackflipper-ecb71.firebaseapp.com',
    storageBucket: 'blackflipper-ecb71.firebasestorage.app',
    measurementId: 'G-9V8BYS9EY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDZbE3Xj0JgAHAEBPqLepcEpBfEfMWHug',
    appId: '1:705573486453:android:07f3a09f4087b32aab9d3c',
    messagingSenderId: '705573486453',
    projectId: 'blackflipper-ecb71',
    storageBucket: 'blackflipper-ecb71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMCKJiU9wnbkFsp1LtrsCAVKRYxY5Vbc',
    appId: '1:705573486453:ios:796b61789a9df5f1ab9d3c',
    messagingSenderId: '705573486453',
    projectId: 'blackflipper-ecb71',
    storageBucket: 'blackflipper-ecb71.firebasestorage.app',
    iosBundleId: 'com.circliks.blackflipper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMCKJiU9wnbkFsp1LtrsCAVKRYxY5Vbc',
    appId: '1:705573486453:ios:796b61789a9df5f1ab9d3c',
    messagingSenderId: '705573486453',
    projectId: 'blackflipper-ecb71',
    storageBucket: 'blackflipper-ecb71.firebasestorage.app',
    iosBundleId: 'com.circliks.blackflipper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3pcfeXc-JVV_y0LyY-iFG1IYaSK0CKH4',
    appId: '1:705573486453:web:35ded5416445c96fab9d3c',
    messagingSenderId: '705573486453',
    projectId: 'blackflipper-ecb71',
    authDomain: 'blackflipper-ecb71.firebaseapp.com',
    storageBucket: 'blackflipper-ecb71.firebasestorage.app',
    measurementId: 'G-X4KL0YQVFZ',
  );
}
